spring:
  application:
    name: hosbee-admin-ui

  profiles:
    active: dev

  mvc:
    view:
      prefix: /public/templates
      suffix: .html

  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

server:
  port: 9030