spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:hosbee
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect